version: '3.4'
services:
  mailserver:
    image: analogic/poste.io
    container_name: poste
    restart: always
    ports:
      - target: 25
        published: 25
        protocol: tcp
        mode: host
      - target: 110
        published: 110
        protocol: tcp
        mode: host
      - target: 143
        published: 143
        protocol: tcp
        mode: host
      - target: 465
        published: 465
        protocol: tcp
        mode: host
      - target: 587
        published: 587
        protocol: tcp
        mode: host
      - target: 993
        published: 993
        protocol: tcp
        mode: host
      - target: 995
        published: 995
        protocol: tcp
        mode: host
      - target: 4190
        published: 4190
        protocol: tcp
        mode: host
      - 0.0.0.0:8081:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- ./html/.well-known/acme-challenge:/opt/www/.well-known/acme-challenge
      - ./data:/data
    environment:
      #- LETSENCRYPT_EMAIL=info@naghiloo.com
      #- LETSENCRYPT_HOST=mail.naghiloo.com
      - VIRTUAL_HOST=mail.naghiloo.com
      - HTTPS=OFF
      - HTTP_PORT=80
    deploy:
      resources:
        limits:
          #cpus: '0.001'
          memory: 1024M
